# Generated by Django 4.0.4 on 2023-12-07 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, verbose_name='Имя игрока 1(загадывает слово)')),
                ('username2', models.CharField(max_length=16, verbose_name='Имя игрока 2(отгадывает слово)')),
                ('word', models.CharField(max_length=25, verbose_name='Загаданное слово')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания игры')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
    ]
