# Generated by Django 4.0.4 on 2023-12-07 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_game_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_game_active',
            field=models.BooleanField(default=True, verbose_name='Игра не закончена?'),
        ),
        migrations.AlterField(
            model_name='game',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт'),
        ),
    ]
