# Generated by Django 4.0.4 on 2023-12-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_game_game_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='encrypted_word',
            field=models.CharField(default=0, max_length=60, verbose_name='Зашифрованное слво'),
            preserve_default=False,
        ),
    ]
