# Generated by Django 4.0.4 on 2023-12-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_game_number_of_mistakes_alter_game_encrypted_word'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-create_date'], 'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AddField(
            model_name='game',
            name='game_save',
            field=models.BooleanField(default=False, verbose_name='Игра сохранена?'),
        ),
    ]
